# See https://domluna.github.io/JuliaFormatter.jl/stable/ for a list of options
margin = 300
remove_extra_newlines = true
trailing_comma = "nothing"
join_lines_based_on_source = true
whitespace_in_kwargs = false
annotate_untyped_fields_with_any = false
align_assignment   = true
align_struct_field = true
align_conditional  = true
align_pair_arrow   = true
align_matrix       = true